cities = [
    "SAN FRANCISCO",
    "CHICAGO",
    "ATLANTA",
    "MONTREAL",
    "WASHINGTON",
    "NEW YORK",
    "LONDON",
    "MADRID",
    "PARIS",
    "ESSEN",
    "MILAN",
    "ST. PETERSBURG",
    "LOS ANGELES",
    "MEXICO CITY",
    "MIAMI",
    "BOGOTA",
    "LIMA",
    "SANTIAGO",
    "BUENOS AIRES",
    "SAO PAULO",
    "LAGOS",
    "KINSHASA",
    "JOHANNESBURG",
    "KHARTOUM",
    "ALGIERS",
    "ISTANBUL",
    "CAIRO",
    "BAGHDAD",
    "MOSCOW",
    "TEHRAN",
    "RIYADH",
    "KARACHI",
    "MUMBAI",
    "DELHI",
    "CHENNAI",
    "KOLKATA",
    "BANGKOK",
    "JAKARTA",
    "HO CHI MINH CITY",
    "HONG KONG",
    "MANILA",
    "SYDNEY",
    "TAIPEI",
    "SHANGHAI",
    "OSAKA",
    "TOKYO",
    "SEOUL",
    "BEIJING",
]

colors = [
    "BLUE",
    "BLACK",
    "YELLOW",
    "RED",
]

city_colors = {
    "SAN FRANCISCO": "BLUE",
    "CHICAGO": "BLUE",
    "ATLANTA": "BLUE",
    "MONTREAL": "BLUE",
    "WASHINGTON": "BLUE",
    "NEW YORK": "BLUE",
    "LONDON": "BLUE",
    "MADRID": "BLUE",
    "PARIS": "BLUE",
    "ESSEN": "BLUE",
    "MILAN": "BLUE",
    "ST. PETERSBURG": "BLUE",
    "LOS ANGELES": "YELLOW",
    "MEXICO CITY": "YELLOW",
    "MIAMI": "YELLOW",
    "BOGOTA": "YELLOW",
    "LIMA": "YELLOW",
    "SANTIAGO": "YELLOW",
    "BUENOS AIRES": "YELLOW",
    "SAO PAULO": "YELLOW",
    "LAGOS": "YELLOW",
    "KINSHASA": "YELLOW",
    "JOHANNESBURG": "YELLOW",
    "KHARTOUM": "YELLOW",
    "ALGIERS": "BLACK",
    "ISTANBUL": "BLACK",
    "CAIRO": "BLACK",
    "BAGHDAD": "BLACK",
    "MOSCOW": "BLACK",
    "TEHRAN": "BLACK",
    "RIYADH": "BLACK",
    "KARACHI": "BLACK",
    "MUMBAI": "BLACK",
    "DELHI": "BLACK",
    "CHENNAI": "BLACK",
    "KOLKATA": "BLACK",
    "BANGKOK": "RED",
    "JAKARTA": "RED",
    "HO CHI MINH CITY": "RED",
    "HONG KONG": "RED",
    "MANILA": "RED",
    "SYDNEY": "RED",
    "TAIPEI": "RED",
    "SHANGHAI": "RED",
    "OSAKA": "RED",
    "TOKYO": "RED",
    "SEOUL": "RED",
    "BEIJING": "RED",
}


