city_names = [
    "SAN FRANCISCO",
    "CHICAGO",
    "ATLANTA",
    "MONTREAL",
    "WASHINGTON",
    "NEW YORK",
    "LONDON",
    "MADRID",
    "PARIS",
    "ESSEN",
    "MILAN",
    "ST. PETERSBURG",
    "LOS ANGELES",
    "MEXICO CITY",
    "MIAMI",
    "BOGOTA",
    "LIMA",
    "SANTIAGO",
    "BUENOS AIRES",
    "SAO PAULO",
    "LAGOS",
    "KINSHASA",
    "JOHANNESBURG",
    "KHARTOUM",
    "ALGIERS",
    "ISTANBUL",
    "CAIRO",
    "BAGHDAD",
    "MOSCOW",
    "TEHRAN",
    "RIYADH",
    "KARACHI",
    "MUMBAI",
    "DELHI",
    "CHENNAI",
    "KOLKATA",
    "BANGKOK",
    "JAKARTA",
    "HO CHI MINH CITY",
    "HONG KONG",
    "MANILA",
    "SYDNEY",
    "TAIPEI",
    "SHANGHAI",
    "OSAKA",
    "TOKYO",
    "SEOUL",
    "BEIJING"
]

colors = [
    "BLUE",
    "BLACK",
    "YELLOW",
    "RED",
]

city_colors = {
    "SAN FRANCISCO": "BLUE",
    "CHICAGO": "BLUE",
    "ATLANTA": "BLUE",
    "MONTREAL": "BLUE",
    "WASHINGTON": "BLUE",
    "NEW YORK": "BLUE",
    "LONDON": "BLUE",
    "MADRID": "BLUE",
    "PARIS": "BLUE",
    "ESSEN": "BLUE",
    "MILAN": "BLUE",
    "ST. PETERSBURG": "BLUE",
    "LOS ANGELES": "YELLOW",
    "MEXICO CITY": "YELLOW",
    "MIAMI": "YELLOW",
    "BOGOTA": "YELLOW",
    "LIMA": "YELLOW",
    "SANTIAGO": "YELLOW",
    "BUENOS AIRES": "YELLOW",
    "SAO PAULO": "YELLOW",
    "LAGOS": "YELLOW",
    "KINSHASA": "YELLOW",
    "JOHANNESBURG": "YELLOW",
    "KHARTOUM": "YELLOW",
    "ALGIERS": "BLACK",
    "ISTANBUL": "BLACK",
    "CAIRO": "BLACK",
    "BAGHDAD": "BLACK",
    "MOSCOW": "BLACK",
    "TEHRAN": "BLACK",
    "RIYADH": "BLACK",
    "KARACHI": "BLACK",
    "MUMBAI": "BLACK",
    "DELHI": "BLACK",
    "CHENNAI": "BLACK",
    "KOLKATA": "BLACK",
    "BANGKOK": "RED",
    "JAKARTA": "RED",
    "HO CHI MINH CITY": "RED",
    "HONG KONG": "RED",
    "MANILA": "RED",
    "SYDNEY": "RED",
    "TAIPEI": "RED",
    "SHANGHAI": "RED",
    "OSAKA": "RED",
    "TOKYO": "RED",
    "SEOUL": "RED",
    "BEIJING": "RED",
}

event_cards = [
    "Resilient Population",
    "One Quiet Night",
    "Forecast",
    "Government Grant",
    "Airlift",
]

roles = [
    "Contingency Planner",
    "Dispatcher",
    "Operations Expert",
    "Quarantine Specialist",
    "Researcher",
    "Medic",
    "Scientist",
]

connected_cities = {
    "SAN FRANCISCO": ["CHICAGO", "MANILA", "TOKYO", "LOS ANGELES"],
    "CHICAGO": ["SAN FRANCISCO", "LOS ANGELES", "MEXICO CITY", "ATLANTA", "MONTREAL"],
    "ATLANTA": ["CHICAGO", "WASHINGTON", "MIAMI"],
    "MONTREAL": ["CHICAGO", "WASHINGTON", "NEW YORK"],
    "WASHINGTON": ["MIAMI", "NEW YORK", "ATLANTA", "MONTREAL"],
    "NEW YORK": ["MONTREAL", "WASHINGTON", "LONDON", "MADRID"],
    "LONDON": ["NEW YORK", "MADRID", "ESSEN", "PARIS"],
    "MADRID": ["NEW YORK", "LONDON", "PARIS", "ALGIERS", "SAO PAULO"],
    "PARIS": ["LONDON", "ESSEN", "MILAN", "ALGIERS", "MADRID"],
    "ESSEN": ["LONDON", "PARIS", "MILAN", "ST. PETERSBURG"],
    "MILAN": ["ESSEN", "PARIS", "ISTANBUL"],
    "ST. PETERSBURG": ["ESSEN", "ISTANBUL", "MOSCOW"],
    "LOS ANGELES": ["SAN FRANCISCO", "CHICAGO", "MEXICO CITY", "SYDNEY"],
    "MEXICO CITY": ["LOS ANGELES", "CHICAGO", "MIAMI", "BOGOTA", "LIMA"],
    "MIAMI": ["WASHINGTON", "ATLANTA", "MEXICO CITY", "BOGOTA"],
    "BOGOTA": ["MEXICO CITY", "MIAMI", "LIMA", "SAO PAULO", "BUENOS AIRES"],
    "LIMA": ["SANTIAGO", "BOGOTA", "MEXICO CITY"],
    "SANTIAGO": ["LIMA"],
    "BUENOS AIRES": ["BOGOTA", "SAO PAULO"],
    "SAO PAULO": ["BUENOS AIRES", "MADRID", "LAGOS"],
    "LAGOS": ["SAO PAULO", "KHARTOUM", "KINSHASA"],
    "KINSHASA": ["LAGOS", "KHARTOUM", "JOHANNESBURG"],
    "JOHANNESBURG": ["KINSHASA", "KHARTOUM"],
    "KHARTOUM": ["LAGOS", "KINSHASA", "JOHANNESBURG", "CAIRO"],
    "ALGIERS": ["MADRID", "PARIS", "ISTANBUL", "CAIRO"],
    "ISTANBUL": ["MILAN", "ALGIERS", "CAIRO", "BAGHDAD", "MOSCOW", "ST. PETERSBURG"],
    "CAIRO": ["ALGIERS", "KHARTOUM", "ISTANBUL", "BAGHDAD", "RIYADH"],
    "BAGHDAD": ["ISTANBUL", "CAIRO", "RIYADH", "KARACHI", "TEHRAN"],
    "MOSCOW": ["ST. PETERSBURG", "ISTANBUL", "TEHRAN"],
    "TEHRAN": ["MOSCOW", "BAGHDAD", "KARACHI", "DELHI"],
    "RIYADH": ["CAIRO", "BAGHDAD", "KARACHI"],
    "KARACHI": ["RIYADH", "BAGHDAD", "TEHRAN", "DELHI", "MUMBAI"],
    "MUMBAI": ["KARACHI", "DELHI", "CHENNAI"],
    "DELHI": ["TEHRAN", "KARACHI", "MUMBAI", "CHENNAI", "KOLKATA"],
    "CHENNAI": ["MUMBAI", "DELHI", "KOLKATA", "BANGKOK", "JAKARTA"],
    "KOLKATA": ["DELHI", "CHENNAI", "BANGKOK", "HONG KONG"],
    "BANGKOK": ["KOLKATA", "CHENNAI", "JAKARTA", "HO CHI MINH CITY", "HONG KONG"],
    "JAKARTA": ["CHENNAI", "BANGKOK", "HO CHI MINH CITY", "SYDNEY"],
    "HO CHI MINH CITY": ["JAKARTA", "BANGKOK", "HONG KONG", "MANILA"],
    "HONG KONG": ["KOLKATA", "BANGKOK", "HO CHI MINH CITY", "MANILA", "TAIPEI", "SHANGHAI"],
    "MANILA": ["TAIPEI", "HONG KONG", "HO CHI MINH CITY", "SYDNEY", "SAN FRANCISCO"],
    "SYDNEY": ["MANILA", "JAKARTA", "LOS ANGELES"],
    "TAIPEI": ["SHANGHAI", "HONG KONG", "MANILA", "OSAKA"],
    "SHANGHAI": ["BEIJING", "SEOUL", "TOKYO", "TAIPEI", "HONG KONG"],
    "OSAKA": ["TOKYO", "TAIPEI"],
    "TOKYO": ["SEOUL", "SHANGHAI", "OSAKA", "SAN FRANCISCO"],
    "SEOUL": ["BEIJING", "SHANGHAI", "TOKYO"],
    "BEIJING": ["SEOUL", "SHANGHAI"],
}

city_coords = {
    "SAN FRANCISCO": (0.0575, 0.2610),
    "CHICAGO": (0.1500, 0.2073),
    "ATLANTA": (0.1788, 0.3122),
    "MONTREAL": (0.2250, 0.2024),
    "WASHINGTON": (0.2563, 0.3049),
    "NEW YORK": (0.2800, 0.2171),
    "LONDON": (0.4163, 0.1317),
    "MADRID": (0.4063, 0.2732),
    "PARIS": (0.4713, 0.2024),
    "ESSEN": (0.4900, 0.1073),
    "MILAN": (0.5200, 0.1756),
    "ST. PETERSBURG": (0.5700, 0.0780),
    "LOS ANGELES": (0.0725, 0.4024),
    "MEXICO CITY": (0.1413, 0.4512),
    "MIAMI": (0.2238, 0.4293),
    "BOGOTA": (0.2175, 0.5732),
    "LIMA": (0.1925, 0.7268),
    "SANTIAGO": (0.2038, 0.8854),
    "BUENOS AIRES": (0.2788, 0.8585),
    "SAO PAULO": (0.3213, 0.7488),
    "LAGOS": (0.4638, 0.5488),
    "KINSHASA": (0.5100, 0.6488),
    "JOHANNESBURG": (0.5513, 0.7927),
    "KHARTOUM": (0.5575, 0.5220),
    "ALGIERS": (0.4875, 0.3537),
    "ISTANBUL": (0.5525, 0.2610),
    "CAIRO": (0.5425, 0.3829),
    "BAGHDAD": (0.6050, 0.3341),
    "MOSCOW": (0.6100, 0.1756),
    "TEHRAN": (0.6600, 0.2439),
    "RIYADH": (0.6138, 0.4634),
    "KARACHI": (0.6750, 0.3805),
    "MUMBAI": (0.6813, 0.4854),
    "DELHI": (0.7288, 0.3390),
    "CHENNAI": (0.7388, 0.5634),
    "KOLKATA": (0.7800, 0.3732),
    "BANGKOK": (0.7900, 0.4951),
    "JAKARTA": (0.7900, 0.6854),
    "HO CHI MINH CITY": (0.8363, 0.5951),
    "HONG KONG": (0.8325, 0.4317),
    "MANILA": (0.9075, 0.5878),
    "SYDNEY": (0.9500, 0.8805),
    "TAIPEI": (0.8913, 0.4098),
    "SHANGHAI": (0.8263, 0.3098),
    "OSAKA": (0.9438, 0.3683),
    "TOKYO": (0.9375, 0.2610),
    "SEOUL": (0.8863, 0.2049),
    "BEIJING": (0.8213, 0.2098),
}

actions = [
    "Drive",
    "Direct Flight",
    "Charter Flight",
    "Shuttle Flight",
    "Build Research Station",
    "Treat Disease",
    "Share Knowledge",
    "Discover Cure",
]